title: My Stories
email: your-email@example.com
description: >-
  Personal stories and musings.
baseurl: ""
url: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
